<template>
  <div class="legal">
    <div class="header">
      <h1 class="header-title">Privacy Policy</h1>
      <div class="header-subtitle">Effective date: September 06, 2021</div>
    </div>
    <div class="paragraph">
      <div class="paragraph-body">
        Lars Boese (&quot;I&quot;, &quot;me&quot;, or &quot;my&quot;) operates
        the
        <a href="https://www.ayakobot.com">https://www.ayakobot.com</a> website
        and the &quot;Ayako#6768&quot; Discord Bot, with unique Discord User-ID
        &quot;650691698409734151&quot; (hereinafter referred to as the
        &quot;Service&quot;).
      </div>
      <div class="paragraph-body">
        This page informs you of my policies regarding the collection, use and
        disclosure of personal data when you use my Service and the choices you
        have associated with that data.
      </div>
      <div class="paragraph-body">
        I use your data to provide and improve the Service. By using the
        Service, you agree to the collection and use of information in
        accordance with this policy. Unless otherwise defined in this Privacy
        Policy, the terms used in this Privacy Policy have the same meanings as
        in my Terms and Conditions, accessible from
        <NuxtLink to="/terms">https://www.ayakobot.com/terms</NuxtLink>
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Definitions</h2>
      <ul class="paragraph-list">
        <li class="paragraph-list-item">
          <div class="paragraph-list-item-text">
            <strong>Service</strong>
          </div>
          <div class="paragraph-list-item-text">
            Service is the
            <a href="https://www.ayakobot.com">https://www.ayakobot.com</a>
            website and the &quot;Ayako#6768&quot; Discord Bot, with unique
            Discord User-ID &quot;650691698409734151&quot; developed and
            maintained by Lars Boese
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-list-item-text">
            <strong>Personal Data</strong>
          </div>
          <div class="paragraph-list-item-text">
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in my possession or likely to come into my possession).
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-list-item-text">
            <strong>Usage Data</strong>
          </div>
          <div class="paragraph-list-item-text">
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-list-item-text">
            <strong>Cookies</strong>
          </div>
          <div class="paragraph-list-item-text">
            Cookies are small files stored on your device (computer or mobile
            device).
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-list-item-text">
            <strong>Data Controller</strong>
          </div>
          <div class="paragraph-list-item-text">
            Data Controller means the natural or legal person who (either alone
            or jointly or in common with other persons) determines the purposes
            for which and the manner in which any personal information are, or
            are to be, processed.
          </div>
          <div class="paragraph-list-item-text">
            For the purpose of this Privacy Policy, we are a Data Controller of
            your Personal Data.
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-list-item-text">
            <strong>Data Processors (or Service Providers)</strong>
          </div>
          <div class="paragraph-list-item-text">
            Data Processor (or Service Provider) means any natural or legal
            person who processes the data on behalf of the Data Controller.
          </div>
          <div class="paragraph-list-item-text">
            I may use the services of various Service Providers in order to
            process your data more effectively.
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-list-item-text">
            <strong>Data Subject (or User)</strong>
          </div>
          <div class="paragraph-list-item-text">
            Data Subject is any living individual who is using my Service and is
            the subject of Personal Data.
          </div>
        </li>
      </ul>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Information Collection and Use</h2>
      <div class="paragraph-body">
        I collect several different types of information for various purposes to
        provide and improve my Service to you.
      </div>
    </div>
    <div class="paragraph">
      <h3>Types of Data Collected</h3>
      <div class="subparagraph">
        <h4>Personal Data</h4>
        <div class="paragraph-body">
          While using my Service, I may ask you to provide me with certain
          personally identifiable information that can be used to contact or
          identify you (&quot;Personal Data&quot;). Personally identifiable
          information may include, but is not limited to:
        </div>
        <ul class="paragraph-list">
          <li class="paragraph-list-item">
            <div class="paragraph-list-item-text">Your Discord User ID</div>
          </li>
          <li class="paragraph-list-item">
            <div class="paragraph-list-item-text">Your Discord User Name</div>
          </li>
          <li class="paragraph-list-item">
            <div class="paragraph-list-item-text">
              Your Joined Discord Servers
            </div>
          </li>
          <li class="paragraph-list-item">
            <div class="paragraph-list-item-text">Cookies and Usage Data</div>
          </li>
        </ul>
        <div class="paragraph-body">
          I may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from me by contacting me.
        </div>
      </div>
      <div class="subparagraph">
        <h4>Usage Data</h4>
        <div class="paragraph-body">
          I may collect information on how the Service is accessed and used
          (&quot;Usage Data&quot;). This Usage Data may include information such
          as your computer&apos;s Internet Protocol address (e.g. IP address),
          browser type, browser version, the pages of my Service that you visit,
          the time and date of your visit, the time spent on those pages, unique
          device identifiers and other diagnostic data. This is all stored by
          google, and not me. I may use email addresses in the future, only to
          send registered users emails about my service.
        </div>
      </div>
      <div class="subparagraph">
        <h4>Tracking &amp; Cookies Data</h4>
        <div class="paragraph-body">
          I use cookies and similar tracking technologies to track the activity
          on my Service and I hold certain information.
        </div>
        <div class="paragraph-body">
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Other tracking technologies are
          also used such as beacons, tags and scripts to collect and track
          information and to improve and analyse my Service.
        </div>
        <div class="paragraph-body">
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of my Service.
        </div>
        <div class="paragraph-body">Examples of Cookies I use:</div>
        <ul class="paragraph-list">
          <li class="paragraph-list-item">
            <div class="paragraph-list-item-text">
              <strong>Session Cookies</strong>
            </div>
            I use Session Cookies to keep you logged in to Discord on my site. I
            also use Google Analytics, which uses cookies for general
            statistical data to help me learn and grow about how to make a
            better user experience.
          </li>
        </ul>
      </div>
      <div class="subparagraph">
        <h4>Message Content Data</h4>
        <div class="paragraph-body">
          My Service may also collect and log information stored in your Message
          Content (&quot;Message Content Data&quot;), depending on whether the
          Server you edit or delete your Message on has the Service Feature
          &quot;Message Logging&quot; enabled. Message Content that can lead
          back to you is not stored outside of Discord. You may opt-out of
          Message Logging by disabling it in your Discord Server or leaving the
          Discord Servers which have this feature enabled. Message Content Data
          may include information such as Message Content, Message Embeds,
          Message Attachments and Message Components.
        </div>
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Use of Data</h2>
      <div class="paragraph-body">
        Lars Boese uses the collected data for various purposes:
      </div>
      <ul class="paragraph-list">
        <li class="paragraph-list-item">To provide and maintain my Service</li>
        <li class="paragraph-list-item">
          To notify you about changes to my Service
        </li>
        <li class="paragraph-list-item">
          To allow you to participate in interactive features of my Service when
          you choose to do so
        </li>
        <li class="paragraph-list-item">To provide customer support</li>
        <li class="paragraph-list-item">
          To gather analysis or valuable information so that I can improve my
          Service
        </li>
        <li class="paragraph-list-item">To monitor the usage of my Service</li>
        <li class="paragraph-list-item">
          To detect, prevent and address technical issues
        </li>
        <li class="paragraph-list-item">
          To provide you with news, special offers and general information about
          other goods, services and events which I offer that are similar to
          those that you have already purchased or enquired about unless you
          have opted not to receive such information
        </li>
      </ul>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">
        Legal Basis for Processing Personal Data under the General Data
        Protection Regulation (GDPR)
      </h2>
      <div class="paragraph-body">
        If you are from the European Economic Area (EEA), Lars Boese legal basis
        for collecting and using the personal information described in this
        Privacy Policy depends on the Personal Data I collect and the specific
        context in which I collect it.
      </div>
      <div class="paragraph-body">
        Lars Boese may process your Personal Data because:
      </div>
      <ul class="paragraph-list">
        <li class="paragraph-list-item">
          I need to perform a contract with you
        </li>
        <li class="paragraph-list-item">
          You have given me permission to do so
        </li>
        <li class="paragraph-list-item">
          The processing is in my legitimate interests and it is not overridden
          by your rights
        </li>
        <li class="paragraph-list-item">For payment processing purposes</li>
        <li class="paragraph-list-item">To comply with the law</li>
      </ul>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Retention of Data</h2>
      <div class="paragraph-body">
        Lars Boese will retain your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. I will retain
        and use your Personal Data to the extent necessary to comply with my
        legal obligations (for example, if I am required to retain your data to
        comply with applicable laws), resolve disputes and enforce my legal
        agreements and policies.
      </div>
      <div class="paragraph-body">
        Lars Boese will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of my Service, or I am legally obligated to retain this
        data for longer periods.
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Transfer of Data</h2>
      <div class="paragraph-body">
        Your information, including Personal Data, may be transferred to - and
        maintained on - computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ from those of your jurisdiction.
      </div>
      <div class="paragraph-body">
        If you are located outside Germany and choose to provide information to
        us, please note that I transfer the data, including Personal Data, to
        Germany and process it there.
      </div>
      <div class="paragraph-body">
        Your consent to this Privacy Policy followed by your submission of such
        information represents your agreement to that transfer.
      </div>
      <div class="paragraph-body">
        Lars Boese will take all the steps reasonably necessary to ensure that
        your data is treated securely and in accordance with this Privacy Policy
        and no transfer of your Personal Data will take place to an organisation
        or a country unless there are adequate controls in place including the
        security of your data and other personal information.
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Disclosure of Data</h2>
      <div class="subparagraph">
        <h3>Legal Requirements</h3>
        <div class="paragraph-body">
          Lars Boese may disclose your Personal Data in the good faith belief
          that such action is necessary to:
        </div>
        <ul class="paragraph-list">
          <li class="paragraph-list-item">comply with a legal obligation</li>
          <li class="paragraph-list-item">
            protect and defend the rights or property of Lars Boese
          </li>
          <li class="paragraph-list-item">
            prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li class="paragraph-list-item">
            protect the personal safety of users of the Service or the public
          </li>
          <li class="paragraph-list-item">protect against legal liability</li>
        </ul>
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Security of Data</h2>
      <div class="paragraph-body">
        The security of your data is important to me but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure. While I strive to use commercially acceptable means to
        protect your Personal Data, I cannot guarantee its absolute security.
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">
        Your Data Protection Rights under the General Data Protection Regulation
        (GDPR)
      </h2>
      <div class="paragraph-body">
        If you are a resident of the European Economic Area (EEA), you have
        certain data protection rights. Lars Boese aims to take reasonable steps
        to allow you to correct, amend, delete or limit the use of your Personal
        Data.
      </div>
      <div class="paragraph-body">
        If you wish to be informed about what Personal Data I hold about you and
        if you want it to be removed from my systems, please contact me.
      </div>
      <div class="paragraph-body">
        In certain circumstances, you have the following data protection rights:
      </div>
      <ul class="paragraph-list">
        <li class="paragraph-list-item">
          <div class="paragraph-body">
            <div class="paragraph-list-item-text">
              <strong>
                The right to access, update or delete the information I have on
                you.
              </strong>
            </div>
            Whenever made possible, you can access, update or request deletion
            of your Personal Data by contacting me.
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-body">
            <div class="paragraph-list-item-text">
              <strong>The right of rectification.</strong>
            </div>
            You have the right to have your information rectified if that
            information is inaccurate or incomplete.
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-body">
            <div class="paragraph-list-item-text">
              <strong>The The right to object.</strong>
            </div>
            You have the right to object to my processing of your Personal Data.
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-body">
            <div class="paragraph-list-item-text">
              <strong>The right of restriction.</strong>
            </div>
            You have the right to request that I restrict the processing of your
            personal information.
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-body">
            <div class="paragraph-list-item-text">
              <strong>The right to data portability.</strong>
            </div>
            You have the right to be provided with a copy of the information I
            have on you in a structured, machine-readable and commonly used
            format.
          </div>
        </li>
        <li class="paragraph-list-item">
          <div class="paragraph-body">
            <div class="paragraph-list-item-text">
              <strong>The right to withdraw consent.</strong>
            </div>
            You also have the right to withdraw your consent at any time where
            Lars Boese relied on your consent to process your personal
            information.
          </div>
        </li>
      </ul>
      <div class="paragraph-body">
        Please note that I may ask you to verify your identity before responding
        to such requests.
      </div>
      <div class="paragraph-body">
        You have the right to complain to a Data Protection Authority about my
        collection and use of your Personal Data. For more information, please
        contact your local data protection authority in the European Economic
        Area (EEA).
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Service Providers</h2>
      <div class="paragraph-body">
        I may employ third party companies and individuals to facilitate my
        Service (&quot;Service Providers&quot;), provide the Service on my
        behalf, perform Service-related services or assist me in analysing how
        my Service is used.
      </div>
      <div class="paragraph-body">
        These third parties have access to your Personal Data only to perform
        these tasks on my behalf and are obligated not to disclose or use it for
        any other purpose.
      </div>
      <div class="subparagraph">
        <h3>Analytics</h3>
        <div class="paragraph-body">
          I may use third-party Service Providers to monitor and analyse the use
          of my Service.
        </div>
        <ul class="paragraph-list">
          <li class="paragraph-list-item">
            <div class="paragraph-body">
              <strong>Google Analytics</strong>
            </div>
            <div class="paragraph-body">
              Google Analytics is a web analytics service offered by Google that
              tracks and reports website traffic. Google uses the data collected
              to track and monitor the use of my Service. This data is shared
              with other Google services. Google may use the collected data to
              contextualise and personalise the ads of its own advertising
              network.
            </div>
            <div class="paragraph-body">
              You can opt-out of having made your activity on the Service
              available to Google Analytics by installing the Google Analytics
              opt-out browser add-on. The add-on prevents the Google Analytics
              JavaScript (ga.js, analytics.js and dc.js) from sharing
              information with Google Analytics about visits activity.
            </div>
            <div class="paragraph-body">
              For more information on the privacy practices of Google, please
              visit the Google Privacy & Terms web page:
              <a href="https://policies.google.com/privacy">
                Google Privacy Policy
              </a>
            </div>
          </li>
        </ul>
      </div>
      <div class="subparagraph">
        <h3>Advertising</h3>
        <div class="paragraph-body">
          I may use third-party Service Providers to show advertisements to you
          to help support and maintain my Service.
        </div>
        <ul class="paragraph-list">
          <li class="paragraph-list-item">
            <div class="paragraph-body">
              <strong>Google AdSense &amp; DoubleClick Cookie</strong>
            </div>
            <div class="paragraph-body">
              Google, as a third party vendor, uses cookies to serve ads on my
              Service. Google&apos;s use of the DoubleClick cookie enables it
              and its partners to serve ads to my users based on their visit to
              my Service or other websites on the Internet.
            </div>
            <div class="paragraph-body">
              You may opt out of the use of the DoubleClick Cookie for
              interest-based advertising by visiting the Google Ads Settings web
              page:
              <a href="https://www.google.com/ads/preferences/">
                Google Preferences
              </a>
            </div>
          </li>
        </ul>
      </div>
      <div class="subparagraph">
        <h3>Payments</h3>
        <div class="paragraph-body">
          I may provide paid products and/or services within the Service. In
          that case, I use third-party services for payment processing (e.g.
          payment processors).
        </div>
        <div class="paragraph-body">
          I will not store or collect your payment card details. That
          information is provided directly to my third-party payment processors
          whose use of your personal information is governed by their Privacy
          Policy. These payment processors adhere to the standards set by
          PCI-DSS as managed by the PCI Security Standards Council, which is a
          joint effort of brands like Visa, MasterCard, American Express and
          Discover. PCI-DSS requirements help ensure the secure handling of
          payment information.
        </div>
        <div class="paragraph-body">
          The payment processors I work with are:
        </div>
        <ul class="paragraph-list">
          <li class="paragraph-list-item">
            <div class="paragraph-body">
              <strong>PayPal</strong>
            </div>
            <div class="paragraph-body">
              Their Privacy Policy can be viewed at
              <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full">
                PayPal Privacy Policy
              </a>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Links to Other Sites</h2>
      <div class="paragraph-body">
        My Service may contain links to other sites that are not operated by me.
        If you click a third party link, you will be directed to that third
        party&apos;s site. I strongly advise you to review the Privacy Policy of
        every site you visit.
      </div>
      <div class="paragraph-body">
        I have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Children&apos;s Privacy</h2>
      <div class="paragraph-body">
        My Service does not address anyone under the age of 13
        (&quot;Children&quot;).
      </div>
      <div class="paragraph-body">
        I do not knowingly collect personally identifiable information from
        anyone under the age of 13. If you are a parent or guardian and you are
        aware that your Child has provided me with Personal Data, please contact
        me. If we become aware that I have collected Personal Data from children
        without verification of parental consent, I take steps to remove that
        information from my servers.
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Changes to This Privacy Policy</h2>
      <div class="paragraph-body">
        I may update my Privacy Policy from time to time. I will notify you of
        any changes by posting the new Privacy Policy on this page.
      </div>
      <div class="paragraph-body">
        I will let you know via email and/or a prominent notice on my Service,
        prior to the change becoming effective and update the &quot;effective
        date&quot; at the top of this Privacy Policy.
      </div>
      <div class="paragraph-body">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </div>
    </div>
    <div class="paragraph">
      <h2 class="paragraph-title">Contact me</h2>
      <div class="paragraph-body">
        If you have any questions about this Privacy Policy, please contact me
        by email:
        <a href="mailto:dev@ayakobot.com">dev@ayakobot.com</a>
      </div>
    </div>
    <span data-ccpa-link="1"> </span>
  </div>
</template>

<style scoped>
@media (max-width: 500px) {
  .legal {
    margin: 0 1rem;
  }
}

@media (min-width: 501px) {
  .legal {
    margin: 0 3rem;
  }
}

a {
  color: #24b329;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}
</style>
